name = "my-scheduled-worker"
main = "src/index.js"
compatibility_date = "2024-03-26"

[triggers]
crons = ["0 * * * *"]  # Runs at the start of every hour

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.